# Wrangler configuration for Open Content Protocol
name = "ocp-webui"
compatibility_date = "2025-06-01"

# Workers configuration with static assets
main = ".svelte-kit/cloudflare/_worker.js"
assets = { directory = ".svelte-kit/cloudflare", binding = "ASSETS" }
