name: Claude Code AI Assistant

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
  issues:
    types: [opened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  claude-code:
    if: |
      github.actor == 'BillDuke13' && (
        github.event_name == 'pull_request' ||
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
        github.event_name == 'issues'
      )
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      issues: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Claude Code
        uses: anthropics/claude-code-action@beta
        with:
          trigger_phrase: "@claude"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          use_bedrock: false
          use_vertex: false
          timeout_minutes: 30
