name: Claude Code AI Assistant

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
  issues:
    types: [opened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  claude-code:
    if: github.actor == 'BillDuke13'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: read
      issues: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Claude Code
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.CLAUDE_API_KEY }}
          github_token: ${{ secrets.CLAUDE_CODE_GITHUB_TOKEN }}
