name: Claude Code AI Assistant

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  claude-code:
    runs-on: ubuntu-latest
    name: Claude Code Assistant
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      issues: write

    steps:
      - name: Setup Claude Code
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.CLAUDE_API_KEY }}
          github_token: ${{ secrets.CLAUDE_CODE_GITHUB_TOKEN }}